server:
  url: http://localhost:5020
  headers:
    Content-Type: application/json
  collections:
    - path: /countries
      headers:
        x-header: value
      requests:
        - method: GET
          statusCode: 404
          file: ./countries.json

        - path: austria
          method: GET
          statusCode: 200
          body: '{ "name": "Austria" }'

        - path: (?<name>[^/]+)
          method: GET
          statusCode: 200
          headers:
            x-message: test
            Content-Type: text/plain
          body: '{ "name": "${name}" }'
      collections:
        - path: (?<countryName>[^/]+)/cities
          requests:
            - method: GET
              statusCode: 200
              file: ./countries/${countryName}/cities.json
    - include: ./people-collection.yaml
