server:
  url: http://localhost:5020
  headers:
    Content-Type: application/json
  mocks:
    - path: /test/(?<id>\d+)
      method: GET
      statusCode: 200
      headers:
        x-message: test
        Content-Type: text/plain
      file: ./content.json
    - path: /test/(?<id>\d+)
      method: DELETE
      statusCode: 204
      body: |
        { "deleted": true }
